apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
        - name: gitlab-auth
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.werf.image.foundraise }}
          command: ['yarn', 'run', 'start', '&', 'yarn', 'run', 'sync']
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          env:
          {{- range $key, $value := .Values.app.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
